# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: cd-openui5-sample-app
resources:
  containers:
  - container: mta
    image: 'ghcr.io/sap/mbtci-java11-node14:latest'
    options: --user 0:0
  - container: cfcli
    image: 'ppiper/cf-cli'
    options: --user 0:0 --privileged
  - container: node
    image: 'geekykaran/headless-chrome-node-docker:latest'
    options: --privileged

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: build
  displayName: Build MTA for Business Technology Platform
  jobs:
    - job: build
      container: mta
      steps:
        - bash: 'mbt --platform cf --mtar MySampleApp.mtar -t . build'
        - publish: $(System.DefaultWorkingDirectory)/.
          artifact: WebApp

- stage: test
  displayName: Run Karma Test Suite
  jobs:
    - job: test
      pool:
        vmImage: 'ubuntu-latest'
      container: node
      steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '>=14'
        - bash: 'npm config set @sap:registry "https://registry.npmjs.org/" && npm install && npm run-script test'
        - publish: $(System.DefaultWorkingDirectory)/.
          artifact: TestResult

- stage: deploy
  displayName: Deployment to SAP Business Technology Platform (cf)
  jobs:
    - job: deploy
      pool:
        vmImage: 'ubuntu-latest'
      container: cfcli
      steps:
        - download: current
          artifact: WebApp 
        - bash: 'cf login -u "$(CF-USER)" -p "$(CF-PASSWORD)" -a "$(CF-API)" -o "$(CF-ORG)" -s "$(CF-SPACE)" && cf deploy $(Pipeline.Workspace)/WebApp/MySampleApp.mtar -f'
